language: cpp
compiler:
  - gcc
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test > /dev/null; fi
  - sudo add-apt-repository -y ppa:boost-latest/ppa > /dev/null
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get upgrade -y -qq > /dev/null
  - sudo apt-get install libboost1.54-all-dev libgtk-3-dev libgtk-3-0 libgtk-3-0-dbg -y > /dev/null
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8 > /dev/null; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
before_script:
  - cmake . -DISDEBUG=true
script:
  - make
notifications:
  irc:
    channels:
      - "irc.esper.net#SteamBotBuilds"
    on_success: always
    on_failure: always
    use_notice: true
  email:
    recipients:
      - lollol222gg@gmail.com
    on_success: always
    on_failure: always
